################################################################
#
#Nasia Boubouraki
#csd4692
#Makefile
#
#
#
###############################################################

all: road.c
	gcc -pthread road.c


clean: a.out
	rm a.out
