##########################################################
#
#Nasia Boubouraki
#csd4692@csd.uoc.gr
#Makefile
#
#########################################################

all: cs345sh.c
	gcc -lreadline cs345sh.c

clean: a.out
	rm a.out
